---
- name: Configure backup servers
  hosts: backup
  roles:
    - pgdump

- name: Configure web servers
  hosts: static
  become: true
  roles:
    - role: sortir
      sortir_populate_cron_hour: "*/12"
      sortir_populate_cron_minute: "0"
      sortir_populate_locations_quantity: "15"
    - role: caddy-ansible
      caddy_systemd_capabilities_enabled: true
      caddy_config: |
        photo.rleo.ovh {
          handle {
            reverse_proxy :8000
          }
        }
        sortir.in {
          handle {
            reverse_proxy :8090
          }
        }
        aronin.app {
          redir https://dental-aronin.webflow.io/
        }
