---
- name: Configure backup servers
  hosts: backup
  roles:
    - pgdump

- name: Configure web servers
  hosts: static
  become: true
  roles:
    - role: caddy-ansible
      caddy_systemd_capabilities_enabled: true
      caddy_config: |
        photo.noxunote.fr, photo.rleo.ovh {
          handle {
            reverse_proxy :8000
          }
        }
        noxunote.fr {
          encode zstd gzip
          handle {
            root * /home/caddy/noxunote.fr
            file_server
          }
        }
        codebar.noxunote.fr, codebar.rleo.ovh {
          encode zstd gzip
          handle {
            reverse_proxy :8080
          }
        }
