---
# This playbook will install the sortir.in service on the remote server and populate the database regularly (by default every 12 hours)

- name: Create sortir.in directory
  ansible.builtin.file:
    path: "{{ sortir_install_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Download sortir.in binaries
  ansible.builtin.get_url:
    url: "https://github.com/leorolland/sortir.in/releases/download/latest/{{ item }}.linux-{{ sortir_arch }}"
    dest: "{{ sortir_install_dir }}/{{ item }}"
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    force: true
  loop:
    - sortir
    - populate

- name: Create systemd service file
  become: true
  ansible.builtin.template:
    src: sortir.service.j2
    dest: /etc/systemd/system/sortir.service
    mode: '0644'

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and restart sortir service
  become: true
  ansible.builtin.systemd:
    name: sortir
    enabled: true
    state: restarted

- name: Add populate to crontab
  ansible.builtin.cron:
    name: "Run sortir.in populate"
    hour: "{{ sortir_populate_cron_hour }}"
    minute: "{{ sortir_populate_cron_minute }}"
    job: "cd {{ sortir_install_dir }} && ./populate {{ sortir_populate_locations_quantity }}"
    user: "{{ ansible_user }}"
